image: python:3.10.12


before_script:
  - echo "Dependencies installation"
  - python3 --version
  - pip3 --version
  - pip3 install -r requirements.txt
  

stages:
  - compile
  - lint

compile:
  stage: compile
  script:
    - echo "Compiling code"
    - find monitor/ -type f -name '*.py' -exec python3 -m py_compile {} + 

lint:
  stage: lint
  script:
    - echo "Checking code quality"
    - find monitor/ -type f -name '*.py' -exec python3 -m pylint --fail-under=5 {} +
