# Generated by Django 5.0 on 2023-12-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Database migration for the initial setup.
    """

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerData',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID'
                )),
                ('champ1', models.CharField(max_length=100)),
                ('champ2', models.IntegerField()),
            ],
            options={
                "verbose_name": "Server Data",
                "verbose_name_plural": "Server Data",
                "doc": "Model representing data related to a server.",
            },
        ),
    ]
